/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_yq_ndkdemo_JNIDemo */

#ifndef _Included_com_example_yq_ndkdemo_JNIDemo
#define _Included_com_example_yq_ndkdemo_JNIDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_yq_ndkdemo_JNIDemo
 * Method:    getHelloWorldText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_yq_ndkdemo_JNIDemo_getHelloWorldText
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
